### ISSUE TITLE
Custom dialer

### ISSUE THREAD

**Issue by lambchr** [beevik/nts#3]
Thanks for the project, it has been really useful! Part of my use case is querying NTS servers, but I am running the code behind a proxy. This causes issues with the key exchange for NTS (NTP queries allow me to add [a custom dialer](https://github.com/beevik/ntp/blob/main/ntp.go#L245)). I wanted to add a custom dialer to NTS for the key exchange to enable me to send requests over my proxy.

**Comment by beevik** [comment]
Pull request accepted and merged.  Thanks!
